Sending build context to Docker daemon  3.584kB
Step 1/8 : FROM ppc64le/ubuntu:16.04
 ---> 17fb9d3bc976
Step 2/8 : MAINTAINER "Meghali Dhoble <dhoblem@us.ibm.com>","Ashwini Shinde <Ashwini.Shinde4@ibm.com>"
 ---> Using cache
 ---> a45ecd608006
Step 3/8 : RUN apt-get update && apt-get install -y apt-utils         build-essential         gcc         g++         llvm         autoconf         clang         corosync-dev         libcorosync-common-dev         cppcheck         crmsh         libbz2-dev         libcfg-dev         libcpg-dev         libdbus-1-dev         libtool         libxml2-dev         libxslt1-dev         git         libglib2.0-dev         make         pkg-config         uuid-dev         libcmap-dev         libquorum-dev         libmcpp-dev         libcmocka-dev         automake         libltdl-dev         libqb-dev         autopoint         gettext
 ---> Using cache
 ---> 23d19a356714
Step 4/8 : RUN apt update &&         apt -y install software-properties-common &&         add-apt-repository ppa:deadsnakes/ppa &&         apt -y install python3.9
 ---> Using cache
 ---> e55881aa826f
Step 5/8 : RUN git clone -b Pacemaker-2.1.5 -- https://github.com/ClusterLabs/pacemaker.git
 ---> Using cache
 ---> d1a7fee230e0
Step 6/8 : WORKDIR pacemaker
 ---> Using cache
 ---> df41b2505347
Step 7/8 : RUN ./autogen.sh && ./configure && make && make install
 ---> Using cache
 ---> fc5c691f244b
Step 8/8 : CMD /etc/init.d/corosync start && /etc/init.d/pacemaker start && /bin/bash
 ---> Using cache
 ---> 86536c6577bb
Successfully built 86536c6577bb
Successfully tagged pacemaker:latest
